FROM python:3.13-slim


WORKDIR /app


# Install Python deps
COPY src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


# Copy app
COPY src/ /app/src/

# /app/data is a volume mount. should not delete on reset
VOLUME ["/app/src/data"]

# Run the simple Flask app directly
CMD ["python", "-m", "src.app"]